### ISSUE TITLE
Traceback errors after installation

### ISSUE THREAD

**Issue by tetrub** [Amenly/onlyfans-scraper#104]
I don't know what else I could try to make this work, anyone has any idea what's wrong? Thanks.

f:\!dl>onlyfans-scraper
Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\user\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\Scripts\onlyfans-scraper.exe\__main__.py", line 4, in <module>
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\onlyfans_scraper\scraper.py", line 23, in <module>
    @Revolution(desc='Getting messages...')
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\revolution\revolution.py", line 215, in __init__
    red = Color('red')
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\revolution\colors.py", line 32, in __new__
    subprocess.call('color', shell=True)
  File "c:\users\user\appdata\local\programs\python\python39\lib\subprocess.py", line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File "c:\users\user\appdata\local\programs\python\python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "c:\users\user\appdata\local\programs\python\python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by Amenly** [comment]
Can you tell me which terminal you're using? (CMD, PowerShell, Windows Terminal, etc.?)
