### ISSUE TITLE
Keep getting error when trying to download a user

### ISSUE THREAD

**Issue by H3ctorZ** [Amenly/onlyfans-scraper#115]
I'm new to all of this so go easy on me. I think everything is correct but once I hit enter I get this error:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/onlyfans-scraper", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/onlyfans_scraper/scraper.py", line 328, in main
    process_prompts()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/onlyfans_scraper/scraper.py", line 269, in process_prompts
    loop()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/onlyfans_scraper/scraper.py", line 219, in process_prompts
    model_id = profile.get_id(headers, username)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/onlyfans_scraper/api/profile.py", line 73, in get_id
    r.raise_for_status()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/httpx/_models.py", line 1423, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: 400 Client Error: Bad Request for url: https://onlyfans.com/api2/v2/users/fairytingz
For more information check: https://httpstatuses.com/400

Don't know what any of that means, can anyone help?

**Comment by H3ctorZ** [comment]
Fixed it, all I did was re-enter:

app-token:

sess:

auth_id:

user agent:

x-bc token:
