### ISSUE TITLE
OF API updated?

### ISSUE THREAD

**Issue by xzr491oo71** [Amenly/onlyfans-scraper#122]
Has OF been updating their API?

A few days ago I got this message when using the "print list" function.
Not really a problem, as I can enter the subscription name manually.

[xxxx@xxxyyy1 OnlyFans]$ onlyfans-scraper 
Using profile: main_profile
? What would you like to do?  Download content from a user
? Choose one of the following options:  Print a list of my subscriptions
Traceback (most recent call last):
  File "/home/xxxx/.local/bin/onlyfans-scraper", line 8, in <module>
    sys.exit(main())
  File "/home/xxxx/.local/lib/python3.9/site-packages/onlyfans_scraper/scraper.py", line 321, in main
    process_prompts()
  File "/home/xxxx/.local/lib/python3.9/site-packages/onlyfans_scraper/scraper.py", line 209, in process_prompts
    subscribe_count = process_me(headers)
  File "/home/xxxx/.local/lib/python3.9/site-packages/onlyfans_scraper/scraper.py", line 189, in process_me
    my_profile = me.scrape_user(headers)
  File "/home/xxxx/.local/lib/python3.9/site-packages/onlyfans_scraper/api/me.py", line 26, in scrape_user
    r.raise_for_status()
  File "/home/xxxx/.local/lib/python3.9/site-packages/httpx/_models.py", line 1405, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: 500 Server Error: Internal Server Error for url: https://onlyfans.com/api2/v2/users/me
For more information check: https://httpstatuses.com/500

A couple days after that I got a 404 client error for a subscription that I knew I had the correct name for.

[xxxx@xxxyyy1 OnlyFans]$ onlyfans-scraper 
Using profile: main_profile
? What would you like to do?  Download content from a user
? Choose one of the following options:  Enter a username
? Enter a model's username:  dZZZZZZe    (name changed from actual)
Traceback (most recent call last):
  File "/home/xxxx/.local/bin/onlyfans-scraper", line 8, in <module>
    sys.exit(main())
  File "/home/xxxx/.local/lib/python3.9/site-packages/onlyfans_scraper/scraper.py", line 321, in main
    process_prompts()
  File "/home/xxxx/.local/lib/python3.9/site-packages/onlyfans_scraper/scraper.py", line 218, in process_prompts
    model_id = profile.get_id(headers, username)
  File "/home/xxxx/.local/lib/python3.9/site-packages/onlyfans_scraper/api/profile.py", line 73, in get_id
    r.raise_for_status()
  File "/home/xxxx/.local/lib/python3.9/site-packages/httpx/_models.py", line 1402, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: 404 Client Error: Not Found for url: https://onlyfans.com/api2/v2/users/dZZZZZZe
For more information check: https://httpstatuses.com/404

**Comment by tetrahydr0** [comment]
{"error":{"code":301,"message":"Wrong user."}} answers to script -> then goes logout

api same, but maybe heads are altered

**Comment by tetrahydr0** [comment]
No clue what i just wrote but my pal sad you'll understand and might have use of it

**Comment by tetrahydr0** [comment]
regenegated all by itself again - just started working out of nowhere after being down since monday
