### ISSUE TITLE
ValueError: math domain error

### ISSUE THREAD

**Issue by BedgeTime** [Amenly/onlyfans-scraper#125]
Not sure what caused this but attempting to scrape a specific user, I was getting this error repeatedly. Dropped the table corresponding to the user's id and that fixed the problem but didn't see any rows that seemed wrong at a cursory glance. I wish I had taken a snapshot of the table beforehand.

``` + Getting messages...
Progress: (0 photos, 0 videos, 0 skipped || 0):   0%|                                            | 0/3 [00:00<?, ?it/s][Errno 11001] getaddrinfo failed
Progress: (0 photos, 0 videos, 0 skipped || 0):   0%|                                            | 0/3 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\onlyfans_scraper\scraper.py", line 332, in <module>
    main()
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\onlyfans_scraper\scraper.py", line 328, in main
    process_prompts()
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\onlyfans_scraper\scraper.py", line 221, in process_prompts
    do_download_content(headers, username, model_id)
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\onlyfans_scraper\scraper.py", line 141, in do_download_content
    asyncio.run(download.process_urls(
  File "C:\Program Files\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\onlyfans_scraper\utils\download.py", line 73, in process_urls
    data = convert_num_bytes(total_bytes_downloaded)
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\onlyfans_scraper\utils\download.py", line 97, in convert_num_bytes
    num_digits = int(math.log10(num_bytes)) + 1
ValueError: math domain error
Task exception was never retrieved
future: <Task finished name='Task-9' coro=<download() done, defined at C:\Users\user\AppData\Roaming\Python\Python39\site-packages\onlyfans_scraper\utils\download.py:104> exception=ClosedResourceError()>
Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\onlyfans_scraper\utils\download.py", line 111, in download
    async with client.stream('GET', url) as r:
  File "C:\Program Files\Python39\lib\contextlib.py", line 181, in __aenter__
    return await self.gen.__anext__()
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\httpx\_client.py", line 1537, in stream
    response = await self.send(
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\httpx\_client.py", line 1586, in send
    response = await self._send_handling_auth(
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\httpx\_client.py", line 1616, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\httpx\_client.py", line 1655, in _send_handling_redirects
    response = await self._send_single_request(request, timeout)
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\httpx\_client.py", line 1699, in _send_single_request
    ) = await transport.handle_async_request(
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\httpx\_transports\default.py", line 281, in handle_async_request
    ) = await self._pool.handle_async_request(
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\httpcore\_async\connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\httpcore\_async\connection.py", line 148, in handle_async_request
    return await self.connection.handle_async_request(
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\httpcore\_async\http11.py", line 128, in handle_async_request
    ) = await self._receive_response(timeout)
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\httpcore\_async\http11.py", line 189, in _receive_response
    event = await self._receive_event(timeout)
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\httpcore\_async\http11.py", line 225, in _receive_event
    data = await self.socket.read(self.READ_NUM_BYTES, timeout)
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\httpcore\_backends\anyio.py", line 60, in read
    return await self.stream.receive(n)
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\anyio\streams\tls.py", line 152, in receive
    data = await self._call_sslobject_method(self._ssl_object.read, max_bytes)
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\anyio\streams\tls.py", line 109, in _call_sslobject_method
    data = await self.transport_stream.receive()
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\anyio\_backends\_asyncio.py", line 1090, in receive
    raise ClosedResourceError from None
anyio.ClosedResourceError
Task exception was never retrieved
future: <Task finished name='Task-8' coro=<download() done, defined at C:\Users\user\AppData\Roaming\Python\Python39\site-packages\onlyfans_scraper\utils\download.py:104> exception=ClosedResourceError()>
Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\onlyfans_scraper\utils\download.py", line 111, in download
    async with client.stream('GET', url) as r:
  File "C:\Program Files\Python39\lib\contextlib.py", line 181, in __aenter__
    return await self.gen.__anext__()
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\httpx\_client.py", line 1537, in stream
    response = await self.send(
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\httpx\_client.py", line 1586, in send
    response = await self._send_handling_auth(
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\httpx\_client.py", line 1616, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\httpx\_client.py", line 1655, in _send_handling_redirects
    response = await self._send_single_request(request, timeout)
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\httpx\_client.py", line 1699, in _send_single_request
    ) = await transport.handle_async_request(
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\httpx\_transports\default.py", line 281, in handle_async_request
    ) = await self._pool.handle_async_request(
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\httpcore\_async\connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\httpcore\_async\connection.py", line 148, in handle_async_request
    return await self.connection.handle_async_request(
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\httpcore\_async\http11.py", line 128, in handle_async_request
    ) = await self._receive_response(timeout)
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\httpcore\_async\http11.py", line 189, in _receive_response
    event = await self._receive_event(timeout)
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\httpcore\_async\http11.py", line 225, in _receive_event
    data = await self.socket.read(self.READ_NUM_BYTES, timeout)
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\httpcore\_backends\anyio.py", line 60, in read
    return await self.stream.receive(n)
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\anyio\streams\tls.py", line 152, in receive
    data = await self._call_sslobject_method(self._ssl_object.read, max_bytes)
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\anyio\streams\tls.py", line 109, in _call_sslobject_method
    data = await self.transport_stream.receive()
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\anyio\_backends\_asyncio.py", line 1090, in receive
    raise ClosedResourceError from None
anyio.ClosedResourceError
```

**Comment by BedgeTime** [comment]
Got the same error again with the same user. Have a copy of the .db file if it's useful or can share the table exported as a csv.
