### ISSUE TITLE
Error 401

### ISSUE THREAD

**Issue by vyrus26** [Amenly/onlyfans-scraper#126]
Hello, a few days ago everything worked fine.

Now i got this, iam posting the full output.

Hello, a few days ago everything worked fine.

Now i got this, iam posting the full output.

`PS D:\X\onlyfans-scraper-1.8.0> python -m onlyfans_scraper.scraper
Using profile: main_profile
? What would you like to do?  Download content from a user
? Choose one of the following options:  Print a list of my subscriptions
Traceback (most recent call last):
  File "C:\Users\Username\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Username\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\X\onlyfans-scraper-1.8.0\onlyfans_scraper\scraper.py", line 325, in <module>
    main()
  File "D:\X\onlyfans-scraper-1.8.0\onlyfans_scraper\scraper.py", line 321, in main
    process_prompts()
  File "D:\X\onlyfans-scraper-1.8.0\onlyfans_scraper\scraper.py", line 209, in process_prompts
    subscribe_count = process_me(headers)
  File "D:\X\onlyfans-scraper-1.8.0\onlyfans_scraper\scraper.py", line 189, in process_me
    my_profile = me.scrape_user(headers)
  File "D:\X\onlyfans-scraper-1.8.0\onlyfans_scraper\api\me.py", line 26, in scrape_user
    r.raise_for_status()
  File "C:\Users\Username\AppData\Local\Programs\Python\Python39\lib\site-packages\httpx\_models.py", line 1423, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: 401 Client Error: Unauthorized for url: https://onlyfans.com/api2/v2/users/me
For more information check: https://httpstatuses.com/401
PS D:\X\onlyfans-scraper-1.8.0>`

What happend here? I cant resolve the Problem...

What happend here? I cant resolve the Problem...

**Comment by tetrahydr0** [comment]
same problem
