### ISSUE TITLE
Unable to do anything

### ISSUE THREAD

**Issue by defnotanalt** [Amenly/onlyfans-scraper#14]
Hey, I followed the instructions and added my tokens to the file using the "edit file" command of the program. However, whenever I try to do anything, I get this error output. I'm on Python 3.9 on Arch Linux though I can't imagine that'd matter.

Error Output:
```? What would you like to do?  Download content from a user
? Choose one of the following options:  Print a list of my subscriptions
Traceback (most recent call last):
  File "/home/noah/.local/bin/onlyfans-scraper", line 8, in <module>
    sys.exit(main())
  File "/home/noah/.local/lib/python3.9/site-packages/onlyfans_scraper/scraper.py", line 321, in main
    process_prompts()
  File "/home/noah/.local/lib/python3.9/site-packages/onlyfans_scraper/scraper.py", line 268, in process_prompts
    loop()
  File "/home/noah/.local/lib/python3.9/site-packages/onlyfans_scraper/scraper.py", line 209, in process_prompts
    subscribe_count = process_me(headers)
  File "/home/noah/.local/lib/python3.9/site-packages/onlyfans_scraper/scraper.py", line 189, in process_me
    my_profile = me.scrape_user(headers)
  File "/home/noah/.local/lib/python3.9/site-packages/onlyfans_scraper/api/me.py", line 26, in scrape_user
    r.raise_for_status()
  File "/home/noah/.local/lib/python3.9/site-packages/httpx/_models.py", line 1402, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: 401 Client Error: Unauthorized for url: https://onlyfans.com/api2/v2/users/me
For more information check: https://httpstatuses.com/401
```

**Comment by Amenly** [comment]
Which version are you using?

It looks like some of your auth information is incorrect since you're getting 401'd

**Comment by Gixxa** [comment]
OF has changed the login - again.

See:

https://github.com/DIGITALCRIMINAL/OnlyFans/issues/1113

**Comment by Amenly** [comment]
That's unfortunate. So far it seems the first value needs to be updated (3 -> 4) and the last portion of the `sign` parameter needs to updated as well (608c48da -> 608fcf2c). But apparently there's a different "static param" for the SHA1 hash that we need. And unfortunately I'm not sure how DC or Hippo figured out how to get that "static param". Not to mention, my weakest language is javascript

**Comment by Gixxa** [comment]
Don't worry about it. I'm sure we'll get a fix again soon. I could even imagine that it might be faster as the reverse engineering groundwork has been set by the last change.

I'm just going to think out of the box a bit but wouldn't a (headless) browser based on Chromium or Firefox work better as a scraper? Not sure if there would be limitations but the whole login should be handled with no issue or am I missing something?

**Comment by Amenly** [comment]
@Gixxa The login part would probably be the hardest part but I'm pretty sure there's a way around it

**Comment by Amenly** [comment]
Should be fine now thanks to DC and Hippothon. If you need to upgrade, just run the following:

```
pip install --upgrade onlyfans-scraper
```

*If you're using macOS/Linux, replace* `pip` *with* `pip3`

==

Also, just wanted to mention that I looked into using selenium to scrape but a problem I ran into is that you won't be able to see the link of the full high quality image (and video) unless you click on the image/video to expand it/play it. I'm not all that familiar with headless browsers, but if having a headless browser click on a video that takes up 1 GB (for example) forces the browser to download all of those bytes, then this alternative just doesn't seem feasible.

**Comment by Gixxa** [comment]
This is what I get after the update and even a reinstall:

```
Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (onlyfans-scraper 1.1.0 (/Users/Michael/Library/Python/3.8/lib/python/site-packages), Requirement.parse('onlyfans-scraper==1.0.1'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/onlyfans-scraper", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3251, in <module>
    def _initialize_master_working_set():
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3263, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/pkg_resources/__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'onlyfans-scraper==1.0.1' distribution was not found and is required by the application
```

**Comment by Amenly** [comment]
I have no idea why you were getting that error. When I upgraded the program on my Mac and ran it, I didn't get anything like that. It just worked

Also, they changed their auth again lol. Upgrade and use `1.2.0`

**Comment by Gixxa** [comment]
Just updated and it worked as expected. I'm also not sure why it did not work this morning.

**Comment by jshxw** [comment]
Hey I'm having similar issues after upgrading this morning:

Using profile: main_profile
Traceback (most recent call last):
  File "c:\users\hawki\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\hawki\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\hawki\AppData\Local\Programs\Python\Python39\Scripts\onlyfans-scraper.exe\__main__.py", line 7, in <module>
  File "c:\users\hawki\appdata\local\programs\python\python39\lib\site-packages\onlyfans_scraper\scraper.py", line 321, in main
    process_prompts()
  File "c:\users\hawki\appdata\local\programs\python\python39\lib\site-packages\onlyfans_scraper\scraper.py", line 199, in process_prompts
    headers = auth.make_headers(auth.read_auth())
  File "c:\users\hawki\appdata\local\programs\python\python39\lib\site-packages\onlyfans_scraper\utils\auth.py", line 31, in read_auth
    auth = json.load(f)
  File "c:\users\hawki\appdata\local\programs\python\python39\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "c:\users\hawki\appdata\local\programs\python\python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "c:\users\hawki\appdata\local\programs\python\python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\users\hawki\appdata\local\programs\python\python39\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 8 column 2 (char 315)

**Comment by Amenly** [comment]
Sounds like it has something to do with your `auth.json` file. I can't really ask you to post it because, if you filled it out, it's going to have sensitive information. You're going to have to open it yourself and check it out. You should be able to find the file in your home directory: `~/.config/onlyfans-scraper/main_profile/auth.json`

Looks like it might have something to do with the `x-bc` part.

**Comment by jshxw** [comment]
> Sounds like it has something to do with your `auth.json` file. I can't really ask you to post it because, if you filled it out, it's going to have sensitive information. You're going to have to open it yourself and check it out. You should be able to find the file in your home directory: `~/.config/onlyfans-scraper/main_profile/auth.json`
> 
> Looks like it might have something to do with the `x-bc` part.


you were right about the file. I looked and noticed the automatically created 'auth.json' file was missing a comma after the user agent portion
