### ISSUE TITLE
Getting error 404. everything else up until I had to do username worked

### ISSUE THREAD

**Issue by mattenox** [Amenly/onlyfans-scraper#145]
? What would you like to do?  Like all of a user's posts
? Enter a model's username:  rileyannemodel
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/bin/onlyfans-scraper", line 10, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/onlyfans_scraper/scraper.py", line 328, in main
    process_prompts()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/onlyfans_scraper/scraper.py", line 240, in process_prompts
    model_id = profile.get_id(headers, username)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/onlyfans_scraper/api/profile.py", line 73, in get_id
    r.raise_for_status()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/httpx/_models.py", line 1508, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '400 Bad Request' for url 'https://onlyfans.com/api2/v2/users/rileyannemodel'
For more information check: https://httpstatuses.com/400

**Comment by mattenox** [comment]
I was trying to like all my own likes on onlyfans.com/rileyannemodel since you can like your own posts, so I chose the option to 'like posts' in the program, but then I ran into the above error like I said when I typed in "rileyannemodel" as the username and it came back with error 400 bad request. Do I need to update anything?

**Comment by mattenox** [comment]
<img width="1357" alt="Screen Shot 2021-12-12 at 4 21 55 AM" src="https://user-images.githubusercontent.com/94671704/145711957-df768d8a-2741-45e3-a523-560779751868.png">

**Comment by mattenox** [comment]
<img width="943" alt="Screen Shot 2021-12-12 at 4 30 13 AM" src="https://user-images.githubusercontent.com/94671704/145712282-94ca569f-4b57-45c4-ac8f-f5168726b0a9.png">
