### ISSUE TITLE
Attribute Error

### ISSUE THREAD

**Issue by buffet69** [Amenly/onlyfans-scraper#15]
It was working fine then after aa download finished tried to run it again and got this.

Successfully created main_profile
Traceback (most recent call last):
  File "./onlyfans-scraper", line 8, in <module>
    sys.exit(main())
  File "/Users/generic/Library/Python/3.8/lib/python/site-packages/onlyfans_scraper/scraper.py", line 321, in main
    process_prompts()
  File "/Users/generic/Library/Python/3.8/lib/python/site-packages/onlyfans_scraper/scraper.py", line 198, in process_prompts
    profiles.print_current_profile()
  File "/Users/generic/Library/Python/3.8/lib/python/site-packages/onlyfans_scraper/utils/profiles.py", line 126, in print_current_profile
    get_profiles()
  File "/Users/generic/Library/Python/3.8/lib/python/site-packages/onlyfans_scraper/utils/profiles.py", line 33, in get_profiles
    move_files(config_path, mainProfile)
  File "/Users/generic/Library/Python/3.8/lib/python/site-packages/onlyfans_scraper/utils/profiles.py", line 64, in move_files
    shutil.move(file, dir_path)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/shutil.py", line 784, in move
    real_dst = os.path.join(dst, _basename(src))
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/shutil.py", line 747, in _basename
    return os.path.basename(path.rstrip(sep))
AttributeError: 'PosixPath' object has no attribute 'rstrip'

**Comment by Amenly** [comment]
Ah interesting. I just looked into it and apparently the `shutil` module doesn't work with `pathlib` objects in any version of Python before 3.9

I'll have to play around with it and replace `shutil` with `pathlib`'s rename method.

**Comment by Amenly** [comment]
It should be fixed now with `1.3.1`
