### ISSUE TITLE
Getting https 500 status error

### ISSUE THREAD

**Issue by dvkrav** [Amenly/onlyfans-scraper#159]
+ Getting highlights...                
 | Getting messages...                Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/onlyfans-scraper", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/onlyfans_scraper/scraper.py", line 328, in main
    process_prompts()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/onlyfans_scraper/scraper.py", line 269, in process_prompts
    loop()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/onlyfans_scraper/scraper.py", line 214, in process_prompts
    do_download_content(headers, username, model_id)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/onlyfans_scraper/scraper.py", line 138, in do_download_content
    combined_urls = process_areas(headers, username, model_id)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/onlyfans_scraper/scraper.py", line 102, in process_areas
    combined_urls = process_areas_all(headers, username, model_id)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/onlyfans_scraper/scraper.py", line 90, in process_areas_all
    messages_urls = process_messages(headers, model_id)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/revolution/revolution.py", line 45, in wrapper
    result = func(*margs, **mkwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/onlyfans_scraper/scraper.py", line 25, in process_messages
    messages_ = messages.scrape_messages(headers, model_id)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/onlyfans_scraper/api/messages.py", line 31, in scrape_messages
    r.raise_for_status()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/httpx/_models.py", line 1508, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Server error '500 Internal Server Error' for url 'https://onlyfans.com/api2/v2/chats/51893127/messages?limit=10&offset=0&order=desc&skip_users=all&skip_users_dups=1'
For more information check: https://httpstatuses.com/500

**Comment by lucasff** [comment]
500 is not really a problem of the library *maybe* but it should treat the exception and not die.
Are you able to make this request via cURL whilst passing the needed parameters for authentication to the API endpoint?
