### ISSUE TITLE
Issue when runnin the scrapper

### ISSUE THREAD

**Issue by vnk24** [Amenly/onlyfans-scraper#167]
```
C:\Users\vinko>onlyfans-scraper
Traceback (most recent call last):
  File "C:\Users\vinko\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\vinko\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\vinko\AppData\Local\Programs\Python\Python310\Scripts\onlyfans-scraper.exe\__main__.py", line 4, in <module>
  File "C:\Users\vinko\AppData\Local\Programs\Python\Python310\lib\site-packages\onlyfans_scraper\scraper.py", line 15, in <module>
    from .api import init, highlights, me, messages, posts, profile, subscriptions
  File "C:\Users\vinko\AppData\Local\Programs\Python\Python310\lib\site-packages\onlyfans_scraper\api\init.py", line 13, in <module>
    from ..utils import auth
  File "C:\Users\vinko\AppData\Local\Programs\Python\Python310\lib\site-packages\onlyfans_scraper\utils\auth.py", line 18, in <module>
    from .profiles import get_current_profile
  File "C:\Users\vinko\AppData\Local\Programs\Python\Python310\lib\site-packages\onlyfans_scraper\utils\profiles.py", line 13, in <module>
    from .config import read_config, update_config
  File "C:\Users\vinko\AppData\Local\Programs\Python\Python310\lib\site-packages\onlyfans_scraper\utils\config.py", line 13, in <module>
    from .prompts import config_prompt
  File "C:\Users\vinko\AppData\Local\Programs\Python\Python310\lib\site-packages\onlyfans_scraper\utils\prompts.py", line 12, in <module>
    from PyInquirer import prompt, Separator
  File "C:\Users\vinko\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInquirer\__init__.py", line 6, in <module>
    from prompt_toolkit.token import Token
  File "C:\Users\vinko\AppData\Local\Programs\Python\Python310\lib\site-packages\prompt_toolkit\__init__.py", line 16, in <module>
    from .interface import CommandLineInterface
  File "C:\Users\vinko\AppData\Local\Programs\Python\Python310\lib\site-packages\prompt_toolkit\interface.py", line 19, in <module>
    from .application import Application, AbortAction
  File "C:\Users\vinko\AppData\Local\Programs\Python\Python310\lib\site-packages\prompt_toolkit\application.py", line 8, in <module>
    from .key_binding.bindings.basic import load_basic_bindings
  File "C:\Users\vinko\AppData\Local\Programs\Python\Python310\lib\site-packages\prompt_toolkit\key_binding\bindings\basic.py", line 9, in <module>
    from prompt_toolkit.renderer import HeightIsUnknownError
  File "C:\Users\vinko\AppData\Local\Programs\Python\Python310\lib\site-packages\prompt_toolkit\renderer.py", line 11, in <module>
    from prompt_toolkit.styles import Style
  File "C:\Users\vinko\AppData\Local\Programs\Python\Python310\lib\site-packages\prompt_toolkit\styles\__init__.py", line 8, in <module>
    from .from_dict import *
  File "C:\Users\vinko\AppData\Local\Programs\Python\Python310\lib\site-packages\prompt_toolkit\styles\from_dict.py", line 9, in <module>
    from collections import Mapping
ImportError: cannot import name 'Mapping' from 'collections' (C:\Users\vinko\AppData\Local\Programs\Python\Python310\lib\collections\__init__.py)
```

**Comment by iLeeaal** [comment]
Now I have a similar error
Traceback (most recent call last):
  File "c:\users\gabriel\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\gabriel\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Gabriel\AppData\Local\Programs\Python\Python39\Scripts\onlyfans-scraper.exe\__main__.py", line 7, in <module>
  File "c:\users\gabriel\appdata\local\programs\python\python39\lib\site-packages\onlyfans_scraper\scraper.py", line 328, in main
    process_prompts()
  File "c:\users\gabriel\appdata\local\programs\python\python39\lib\site-packages\onlyfans_scraper\scraper.py", line 210, in process_prompts
    subscribe_count = process_me(headers)
  File "c:\users\gabriel\appdata\local\programs\python\python39\lib\site-packages\onlyfans_scraper\scraper.py", line 189, in process_me
    my_profile = me.scrape_user(headers)
  File "c:\users\gabriel\appdata\local\programs\python\python39\lib\site-packages\onlyfans_scraper\api\me.py", line 26, in scrape_user
    r.raise_for_status()
  File "c:\users\gabriel\appdata\local\programs\python\python39\lib\site-packages\httpx\_models.py", line 1510, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '401 Unauthorized' for url 'https://onlyfans.com/api2/v2/users/me'
For more information check: https://httpstatuses.com/401

**Comment by vnk24** [comment]
Not sure if you have the same error as me. But I was able to fix it by downgrading python. I went from 3.10 to 3.9.

**Comment by iLeeaal** [comment]
Unfortunately it's not the same problem, I already had version 3.9, I even reinstalled it but it didn't help

**Comment by jonexume** [comment]
I am having the same exact issue like the person who originally submitted this ticket.  If anyone has some fixes.  It would be greatly appreciated.
