### ISSUE TITLE
Nothing work all of the sudden, reinstalling everything gives me "import error"

### ISSUE THREAD

**Issue by Crazylocust** [Amenly/onlyfans-scraper#185]
Hi, I have only 3 days left and I have been trying to fix it for days before the OF subscription is over.

So now, everytime I try to reinstall, I have no error message. But then when I launch onlyfans-scraper I got this.

Can someone help?

Traceback (most recent call last):
  File "C:\Users\arawn\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\arawn\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\arawn\AppData\Local\Programs\Python\Python310\Scripts\onlyfans-scraper.exe\__main__.py", line 4, in <module>
  File "C:\Users\arawn\AppData\Local\Programs\Python\Python310\lib\site-packages\onlyfans_scraper\scraper.py", line 15, in <module>
    from .api import init, highlights, me, messages, posts, profile, subscriptions
  File "C:\Users\arawn\AppData\Local\Programs\Python\Python310\lib\site-packages\onlyfans_scraper\api\init.py", line 13, in <module>
    from ..utils import auth
  File "C:\Users\arawn\AppData\Local\Programs\Python\Python310\lib\site-packages\onlyfans_scraper\utils\auth.py", line 18, in <module>
    from .profiles import get_current_profile
  File "C:\Users\arawn\AppData\Local\Programs\Python\Python310\lib\site-packages\onlyfans_scraper\utils\profiles.py", line 13, in <module>
    from .config import read_config, update_config
  File "C:\Users\arawn\AppData\Local\Programs\Python\Python310\lib\site-packages\onlyfans_scraper\utils\config.py", line 13, in <module>
    from .prompts import config_prompt
  File "C:\Users\arawn\AppData\Local\Programs\Python\Python310\lib\site-packages\onlyfans_scraper\utils\prompts.py", line 12, in <module>
    from PyInquirer import prompt, Separator
  File "C:\Users\arawn\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInquirer\__init__.py", line 6, in <module>
    from prompt_toolkit.token import Token
  File "C:\Users\arawn\AppData\Local\Programs\Python\Python310\lib\site-packages\prompt_toolkit\__init__.py", line 16, in <module>
    from .interface import CommandLineInterface
  File "C:\Users\arawn\AppData\Local\Programs\Python\Python310\lib\site-packages\prompt_toolkit\interface.py", line 19, in <module>
    from .application import Application, AbortAction
  File "C:\Users\arawn\AppData\Local\Programs\Python\Python310\lib\site-packages\prompt_toolkit\application.py", line 8, in <module>
    from .key_binding.bindings.basic import load_basic_bindings
  File "C:\Users\arawn\AppData\Local\Programs\Python\Python310\lib\site-packages\prompt_toolkit\key_binding\bindings\basic.py", line 9, in <module>
    from prompt_toolkit.renderer import HeightIsUnknownError
  File "C:\Users\arawn\AppData\Local\Programs\Python\Python310\lib\site-packages\prompt_toolkit\renderer.py", line 11, in <module>
    from prompt_toolkit.styles import Style
  File "C:\Users\arawn\AppData\Local\Programs\Python\Python310\lib\site-packages\prompt_toolkit\styles\__init__.py", line 8, in <module>
    from .from_dict import *
  File "C:\Users\arawn\AppData\Local\Programs\Python\Python310\lib\site-packages\prompt_toolkit\styles\from_dict.py", line 9, in <module>
    from collections import Mapping
ImportError: cannot import name 'Mapping' from 'collections' (C:\Users\arawn\AppData\Local\Programs\Python\Python310\lib\collections\__init__.py)

**Comment by Crazylocust** [comment]
Ok find it myself, I had to go back to 3.9
