### ISSUE TITLE
ImportError: cannot import name 'Mapping' from 'collections'

### ISSUE THREAD

**Issue by raleighlittles** [Amenly/onlyfans-scraper#188]
I'm getting this error everytime I try to run `onlyfans-scraper`.

```
Traceback (most recent call last):
  File "/home/raleigh/.local/bin/onlyfans-scraper", line 5, in <module>
    from onlyfans_scraper.scraper import main
  File "/home/raleigh/.local/lib/python3.10/site-packages/onlyfans_scraper/scraper.py", line 15, in <module>
    from .api import init, highlights, me, messages, posts, profile, subscriptions
  File "/home/raleigh/.local/lib/python3.10/site-packages/onlyfans_scraper/api/init.py", line 13, in <module>
    from ..utils import auth
  File "/home/raleigh/.local/lib/python3.10/site-packages/onlyfans_scraper/utils/auth.py", line 18, in <module>
    from .profiles import get_current_profile
  File "/home/raleigh/.local/lib/python3.10/site-packages/onlyfans_scraper/utils/profiles.py", line 13, in <module>
    from .config import read_config, update_config
  File "/home/raleigh/.local/lib/python3.10/site-packages/onlyfans_scraper/utils/config.py", line 13, in <module>
    from .prompts import config_prompt
  File "/home/raleigh/.local/lib/python3.10/site-packages/onlyfans_scraper/utils/prompts.py", line 12, in <module>
    from PyInquirer import prompt, Separator
  File "/home/raleigh/.local/lib/python3.10/site-packages/PyInquirer/__init__.py", line 6, in <module>
    from prompt_toolkit.token import Token
  File "/home/raleigh/.local/lib/python3.10/site-packages/prompt_toolkit/__init__.py", line 16, in <module>
    from .interface import CommandLineInterface
  File "/home/raleigh/.local/lib/python3.10/site-packages/prompt_toolkit/interface.py", line 19, in <module>
    from .application import Application, AbortAction
  File "/home/raleigh/.local/lib/python3.10/site-packages/prompt_toolkit/application.py", line 8, in <module>
    from .key_binding.bindings.basic import load_basic_bindings
  File "/home/raleigh/.local/lib/python3.10/site-packages/prompt_toolkit/key_binding/bindings/basic.py", line 9, in <module>
    from prompt_toolkit.renderer import HeightIsUnknownError
  File "/home/raleigh/.local/lib/python3.10/site-packages/prompt_toolkit/renderer.py", line 11, in <module>
    from prompt_toolkit.styles import Style
  File "/home/raleigh/.local/lib/python3.10/site-packages/prompt_toolkit/styles/__init__.py", line 8, in <module>
    from .from_dict import *
  File "/home/raleigh/.local/lib/python3.10/site-packages/prompt_toolkit/styles/from_dict.py", line 9, in <module>
    from collections import Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
```

Here's my system information:

Ubuntu 22.04 LTS x86_64, running: 5.15.0-35-generic 
Python 3.10.4
pip 22.0.2 from /usr/lib/python3/dist-packages/pip (python 3.10)

**Comment by fc1935** [comment]
I'm also having the same error - had it working on my RPi4B but can't work out the way to change its storage directory to external storage.

Have installed on my Windows 10 PC and also now having the same issue as you:

`Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python310\Scripts\onlyfans-scraper.exe\__main__.py", line 4, in <module>
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python310\lib\site-packages\onlyfans_scraper\scraper.py", line 15, in <module>
    from .api import init, highlights, me, messages, posts, profile, subscriptions
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python310\lib\site-packages\onlyfans_scraper\api\init.py", line 13, in <module>
    from ..utils import auth
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python310\lib\site-packages\onlyfans_scraper\utils\auth.py", line 18, in <module>
    from .profiles import get_current_profile
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python310\lib\site-packages\onlyfans_scraper\utils\profiles.py", line 13, in <module>
    from .config import read_config, update_config
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python310\lib\site-packages\onlyfans_scraper\utils\config.py", line 13, in <module>
    from .prompts import config_prompt
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python310\lib\site-packages\onlyfans_scraper\utils\prompts.py", line 12, in <module>
    from PyInquirer import prompt, Separator
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInquirer\__init__.py", line 6, in <module>
    from prompt_toolkit.token import Token
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python310\lib\site-packages\prompt_toolkit\__init__.py", line 16, in <module>
    from .interface import CommandLineInterface
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python310\lib\site-packages\prompt_toolkit\interface.py", line 19, in <module>
    from .application import Application, AbortAction
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python310\lib\site-packages\prompt_toolkit\application.py", line 8, in <module>
    from .key_binding.bindings.basic import load_basic_bindings
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python310\lib\site-packages\prompt_toolkit\key_binding\bindings\basic.py", line 9, in <module>
    from prompt_toolkit.renderer import HeightIsUnknownError
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python310\lib\site-packages\prompt_toolkit\renderer.py", line 11, in <module>
    from prompt_toolkit.styles import Style
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python310\lib\site-packages\prompt_toolkit\styles\__init__.py", line 8, in <module>
    from .from_dict import *
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python310\lib\site-packages\prompt_toolkit\styles\from_dict.py", line 9, in <module>
    from collections import Mapping
ImportError: cannot import name 'Mapping' from 'collections' (C:\Users\Owner\AppData\Local\Programs\Python\Python310\lib\collections\__init__.py)`

Windows 10
Python 3.10.5
pip 22.0.4

**Comment by Hate9** [comment]
I am also having the issue.
```
Traceback (most recent call last):
  File "/home/mabel/.local/bin/onlyfans-scraper", line 5, in <module>
    from onlyfans_scraper.scraper import main
  File "/home/mabel/.local/lib/python3.10/site-packages/onlyfans_scraper/scraper.py", line 15, in <module>
    from .api import init, highlights, me, messages, posts, profile, subscriptions
  File "/home/mabel/.local/lib/python3.10/site-packages/onlyfans_scraper/api/init.py", line 13, in <module>
    from ..utils import auth
  File "/home/mabel/.local/lib/python3.10/site-packages/onlyfans_scraper/utils/auth.py", line 18, in <module>
    from .profiles import get_current_profile
  File "/home/mabel/.local/lib/python3.10/site-packages/onlyfans_scraper/utils/profiles.py", line 13, in <module>
    from .config import read_config, update_config
  File "/home/mabel/.local/lib/python3.10/site-packages/onlyfans_scraper/utils/config.py", line 13, in <module>
    from .prompts import config_prompt
  File "/home/mabel/.local/lib/python3.10/site-packages/onlyfans_scraper/utils/prompts.py", line 12, in <module>
    from PyInquirer import prompt, Separator
  File "/home/mabel/.local/lib/python3.10/site-packages/PyInquirer/__init__.py", line 6, in <module>
    from prompt_toolkit.token import Token
  File "/home/mabel/.local/lib/python3.10/site-packages/prompt_toolkit/__init__.py", line 16, in <module>
    from .interface import CommandLineInterface
  File "/home/mabel/.local/lib/python3.10/site-packages/prompt_toolkit/interface.py", line 19, in <module>
    from .application import Application, AbortAction
  File "/home/mabel/.local/lib/python3.10/site-packages/prompt_toolkit/application.py", line 8, in <module>
    from .key_binding.bindings.basic import load_basic_bindings
  File "/home/mabel/.local/lib/python3.10/site-packages/prompt_toolkit/key_binding/bindings/basic.py", line 9, in <module>
    from prompt_toolkit.renderer import HeightIsUnknownError
  File "/home/mabel/.local/lib/python3.10/site-packages/prompt_toolkit/renderer.py", line 11, in <module>
    from prompt_toolkit.styles import Style
  File "/home/mabel/.local/lib/python3.10/site-packages/prompt_toolkit/styles/__init__.py", line 8, in <module>
    from .from_dict import *
  File "/home/mabel/.local/lib/python3.10/site-packages/prompt_toolkit/styles/from_dict.py", line 9, in <module>
    from collections import Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
```
EndeavourOS Linux x86_64 on linux 5.18.11-xanmod1-1
Python 3.10.5
pip 22.2
