### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by xxx-uploaded** [Amenly/onlyfans-scraper#196]
- 164 posts
 -- 106 photos
 -- 146 videos
 -- 0 audios
- 0 archived posts
 + Getting pinned media...
 + Getting timeline media...
 + Getting archived media...
 \ Getting highlights...                        Traceback (most recent call last):
  File "c:\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python39\Scripts\onlyfans-scraper.exe\__main__.py", line 7, in <module>
  File "c:\python39\lib\site-packages\onlyfans_scraper\scraper.py", line 328, in main
    process_prompts()
  File "c:\python39\lib\site-packages\onlyfans_scraper\scraper.py", line 269, in process_prompts
    loop()
  File "c:\python39\lib\site-packages\onlyfans_scraper\scraper.py", line 214, in process_prompts
    do_download_content(headers, username, model_id)
  File "c:\python39\lib\site-packages\onlyfans_scraper\scraper.py", line 138, in do_download_content
    combined_urls = process_areas(headers, username, model_id)
  File "c:\python39\lib\site-packages\onlyfans_scraper\scraper.py", line 102, in process_areas
    combined_urls = process_areas_all(headers, username, model_id)
  File "c:\python39\lib\site-packages\onlyfans_scraper\scraper.py", line 89, in process_areas_all
    highlights_urls = process_highlights(headers, model_id)
  File "c:\python39\lib\site-packages\revolution\revolution.py", line 45, in wrapper
    result = func(*margs, **mkwargs)
  File "c:\python39\lib\site-packages\onlyfans_scraper\scraper.py", line 38, in process_highlights
    highlights_ids = highlights.parse_highlights(highlights_)
  File "c:\python39\lib\site-packages\onlyfans_scraper\api\highlights.py", line 42, in parse_highlights
    highlight_ids = [highlight['id'] for highlight in highlights]
  File "c:\python39\lib\site-packages\onlyfans_scraper\api\highlights.py", line 42, in <listcomp>
    highlight_ids = [highlight['id'] for highlight in highlights]
TypeError: string indices must be integers

**Comment by taux1c** [comment]
This was already fixed. You just need to update.

**Comment by davidgomezcol** [comment]
Hi!. This issue seems to be still happening.. I updated the package using `pip install --upgrade onlyfans-scraper` and the error is still appearing..

**Comment by taux1c** [comment]
It's possible that the pip package hasn't been updated. (I've never maintained a package repo.) Try taking the code from here and using it.

**Comment by taux1c** [comment]
Alternatively, you could change line 42 in c:\python39\lib\site-packages\onlyfans_scraper\api\highlights.py to

 `highlight_ids = [highlight['id'] for highlight in highlights.get("data")]`

**Comment by xxx-uploaded** [comment]
> Alternatively, you could change line 42 in c:\python39\lib\site-packages\onlyfans_scraper\api\highlights.py to
> 
> `highlight_ids = [highlight['id'] for highlight in highlights.get("data")]`

Fixed, but still an error

**Comment by taux1c** [comment]
The same error?

**Comment by tdex89** [comment]
I'm getting the same error even after the fix.

**Comment by xxx-uploaded** [comment]
> The same error?

 NUM         USERNAME                       ID             EXPIRES ON
   1        sexylexxxyp               25003251     August 23, 2022 02:22:52 PM

Enter the number next to the user whose content you would like to download:
> 1
[?] Which area(s) would you like to scrape? (Press ENTER to continue)  [All]
Name: Lexi #1 Puerto Rican on OF🤪💦 | Username: sexylexxxyp | ID: 25003251 | Joined: March 20, 2020
- 7320 posts
 -- 4277 photos
 -- 2114 videos
 -- 0 audios
- 1191 archived posts
 + Getting pinned media...
 + Getting timeline media...
 + Getting archived media...
 - Getting highlights...                        Traceback (most recent call last):
  File "c:\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python39\Scripts\onlyfans-scraper.exe\__main__.py", line 7, in <module>
  File "c:\python39\lib\site-packages\onlyfans_scraper\scraper.py", line 328, in main
    process_prompts()
  File "c:\python39\lib\site-packages\onlyfans_scraper\scraper.py", line 214, in process_prompts
    do_download_content(headers, username, model_id)
  File "c:\python39\lib\site-packages\onlyfans_scraper\scraper.py", line 138, in do_download_content
     combined_urls = process_areas(headers, username, model_id)\
  File "c:\python39\lib\site-packages\onlyfans_scraper\scraper.py", line 102, in process_areas
 Getting highlights...                            combined_urls = process_areas_all(headers, username, model_id)
  File "c:\python39\lib\site-packages\onlyfans_scraper\scraper.py", line 89, in process_areas_all
    highlights_urls = process_highlights(headers, model_id)
  File "c:\python39\lib\site-packages\revolution\revolution.py", line 45, in wrapper
    result = func(*margs, **mkwargs)
  File "c:\python39\lib\site-packages\onlyfans_scraper\scraper.py", line 38, in process_highlights
    highlights_ids = highlights.parse_highlights(highlights_)
  File "c:\python39\lib\site-packages\onlyfans_scraper\api\highlights.py", line 42, in parse_highlights
    highlight_ids = [highlight['id'] for highlight in highlights]
  File "c:\python39\lib\site-packages\onlyfans_scraper\api\highlights.py", line 42, in <listcomp>
    highlight_ids = [highlight['id'] for highlight in highlights]
TypeError: string indices must be integers

**Comment by tdex89** [comment]
I'm running it on mac.

**Comment by tdo21t** [comment]
I have a similar error but also with Status - Down.

**Comment by taux1c** [comment]
> Made a quick fix for this issue, let me know if it works and ill make a pull request.
> 
> 
> 
> anonfiles com/d379Fe06y3/onlyfansdownloader_exe

Pretty sure this is spam, I wouldn't try anything outside of GitHub.

**Comment by DankMemeGuy** [comment]
Same issue for me

**Comment by DankMemeGuy** [comment]
> Alternatively, you could change line 42 in c:\python39\lib\site-packages\onlyfans_scraper\api\highlights.py to
> 
> `highlight_ids = [highlight['id'] for highlight in highlights.get("data")]`

This solved my issue. Can you comit that code into the main?

**Comment by taux1c** [comment]
> > Alternatively, you could change line 42 in c:\python39\lib\site-packages\onlyfans_scraper\api\highlights.py to
> 
> > 
> 
> > `highlight_ids = [highlight['id'] for highlight in highlights.get("data")]`
> 
> 
> 
> This solved my issue. Can you comit that code into the main? 

It's in main but you can't get it with pip because the pip repo hasn't been updated.

**Comment by eXqusic** [comment]
> anonfiles.com/d379Fe06y3/onlyfansdownloader_exe

Its not spam, I was just trying to help out by fixing the bug.

**Comment by davidgomezcol** [comment]
I would like to run using the code, but I'm having issues with the relatives imports.. do you have a special way to run the program using the source files?

**Comment by taux1c** [comment]
Honestly, I have no clue if you're on windows. I would suggest looking on youtube for something like how to run a python program on windows. If you are on linux you can just git clone the repo url and python3 setup.py I think. 🤔

**Comment by davidgomezcol** [comment]
Hi!. No, I'm a Mac user. I'm trying to run it using Python 3.8.4. Running the setup.py, it install some things but when trying to run it, same error.. Will have to wait for the update of the pip package I think..

**Comment by sideloading** [comment]
my process on ubuntu was simple:
```
1. pip uninstall onlyfans-scraper
2. clone the repo
3. modify line 42 in onlyfans_scraper/api/highlights.py
4. reinstall after modifying the file: python setup.py install
5. run onlyfans-scraper
```

**Comment by taux1c** [comment]
> 

I'm not sure if that update will ever come. Most devs have lives outside of git and are on here once or twice a year. Once a good package is written it's not worth it to us to maintain it. Most scripts aren't maintained.

**Comment by MalbinR** [comment]
> highlight_ids = [highlight['id'] for highlight in highlights.get("data")]

That worked for me, THANK YOU!

**Comment by taux1c** [comment]
> > highlight_ids = [highlight['id'] for highlight in highlights.get("data")]
> 
> 
> 
> That worked for me, THANK YOU!

You're welcome, ultimately it's just that the ids are stored in an object list now instead of a list.

**Comment by runaroundhome** [comment]
If you're a Mac user and installed it via `pip3 install onlyfans-scraper`, then the file to update is here `/usr/local/lib/python3.9/site-packages/onlyfans_scraper/api/highlights.py`

Then find `highlight_ids = [highlight['id'] for highlight in highlights]` on (probably) line 42, and replace it with `highlight_ids = [highlight['id'] for highlight in highlights.get("data")]`

<img width="1080" alt="image" src="https://user-images.githubusercontent.com/16973228/182015532-113a6eef-6e75-4ee2-833a-13c2d73cca85.png">
