### ISSUE TITLE
String indices must be integers

### ISSUE THREAD

**Issue by zurovec** [Amenly/onlyfans-scraper#199]
Hi, I get the following traceback when downloading all content from a user. It's a subscription that just started today.

```
Traceback (most recent call last):
  File "/usr/local/bin/onlyfans-scraper", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/onlyfans_scraper/scraper.py", line 328, in main
    process_prompts()
  File "/usr/local/lib/python3.8/dist-packages/onlyfans_scraper/scraper.py", line 214, in process_prompts
    do_download_content(headers, username, model_id)
  File "/usr/local/lib/python3.8/dist-packages/onlyfans_scraper/scraper.py", line 138, in do_download_content
    combined_urls = process_areas(headers, username, model_id)
  File "/usr/local/lib/python3.8/dist-packages/onlyfans_scraper/scraper.py", line 102, in process_areas
    combined_urls = process_areas_all(headers, username, model_id)
  File "/usr/local/lib/python3.8/dist-packages/onlyfans_scraper/scraper.py", line 89, in process_areas_all
    highlights_urls = process_highlights(headers, model_id)
  File "/usr/local/lib/python3.8/dist-packages/revolution/revolution.py", line 45, in wrapper
    result = func(*margs, **mkwargs)
  File "/usr/local/lib/python3.8/dist-packages/onlyfans_scraper/scraper.py", line 38, in process_highlights
    highlights_ids = highlights.parse_highlights(highlights_)
  File "/usr/local/lib/python3.8/dist-packages/onlyfans_scraper/api/highlights.py", line 42, in parse_highlights
    highlight_ids = [highlight['id'] for highlight in highlights]
  File "/usr/local/lib/python3.8/dist-packages/onlyfans_scraper/api/highlights.py", line 42, in <listcomp>
    highlight_ids = [highlight['id'] for highlight in highlights]
TypeError: string indices must be integers
```

**Comment by brucynl** [comment]
I'm see the same problem

**Comment by taux1c** [comment]
Ahh yes and you decided to open a new issue instead of reviewing the current one with almost the exact same title because ... ?

**Comment by zurovec** [comment]
Sorry, didn't see

**Comment by zurovec** [comment]
Duplicaten issue

**Comment by taux1c** [comment]
You're good my dude, just wanted to point out that you should always check for issues first.
