### ISSUE TITLE
401 error message

### ISSUE THREAD

**Issue by NillaMouse** [Amenly/onlyfans-scraper#28]
Hi,

I installed the script and when running to scrape the models, was presented with the following error log

Traceback (most recent call last):
  File "c:\users\warre\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\warre\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\warre\AppData\Local\Programs\Python\Python39\Scripts\onlyfans-scraper.exe\__main__.py", line 7, in <module>
  File "c:\users\warre\appdata\local\programs\python\python39\lib\site-packages\onlyfans_scraper\scraper.py", line 321, in main
    process_prompts()
  File "c:\users\warre\appdata\local\programs\python\python39\lib\site-packages\onlyfans_scraper\scraper.py", line 303, in process_prompts
    loop()
  File "c:\users\warre\appdata\local\programs\python\python39\lib\site-packages\onlyfans_scraper\scraper.py", line 227, in process_prompts
    subscribe_count = process_me(headers)
  File "c:\users\warre\appdata\local\programs\python\python39\lib\site-packages\onlyfans_scraper\scraper.py", line 189, in process_me
    my_profile = me.scrape_user(headers)
  File "c:\users\warre\appdata\local\programs\python\python39\lib\site-packages\onlyfans_scraper\api\me.py", line 26, in scrape_user
    r.raise_for_status()
  File "c:\users\warre\appdata\local\programs\python\python39\lib\site-packages\httpx\_models.py", line 1402, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: 401 Client Error: Unauthorized for url: https://onlyfans.com/api2/v2/users/me

Any feedback / suggestions appreciated.

**Comment by buffet69** [comment]
Same here.  Just started happening this morning.

**Comment by Amenly** [comment]
Try again with the latest release `1.5.0`: 

```
pip install --upgrade onlyfans-scraper
```

**Comment by buffet69** [comment]
Same message.

**Comment by Amenly** [comment]
I'm not getting an error. Did your auth info change by any chance?

**Comment by buffet69** [comment]
I didn’t change it, but I can edit the file and test.

**Comment by buffet69** [comment]
Sess cookie changed.  Now getting a 400 error.

**Comment by buffet69** [comment]
It actually keeps bouncing back to 401.  The sess cookie keeps changing.

**Comment by Amenly** [comment]
If your sess cookie is changing then that means you keep having to sign in on their website right? IMO, that means something in your `auth.json` isn't right. I'm not having any issues at all.

**Comment by buffet69** [comment]
Something must be weird. Every time I run it I get a 401 and then need to reauthenticate in my browser.

**Comment by itsdavee316** [comment]
I've reset my auth.json, entered all data from scratch. Full uninstall of 1.3.1 and install of 1.7.1. Still getting 401 error.
[scraper error.txt](https://github.com/Amenly/onlyfans-scraper/files/6487719/scraper.error.txt)

**Comment by Amenly** [comment]
It's on your end. I just tested it with an account that has 2FA enabled and one that doesn't. They both worked. Recheck your auth

**Comment by itsdavee316** [comment]
> It's on your end. I just tested it with an account that has 2FA enabled and one that doesn't. They both worked. Recheck your auth

Does it work better with 2FA enabled, is there a pro/con when using the script?
