### ISSUE TITLE
cannot find request_auth.json in main_profile

### ISSUE THREAD

**Issue by adithyarao121** [Amenly/onlyfans-scraper#31]
Using profile: main_profile
Traceback (most recent call last):
  File "c:\users\adith\anaconda3\envs\trials\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\adith\anaconda3\envs\trials\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\adith\anaconda3\envs\trials\Scripts\onlyfans-scraper.exe\__main__.py", line 7, in <module>
  File "c:\users\adith\anaconda3\envs\trials\lib\site-packages\onlyfans_scraper\scraper.py", line 321, in main
    process_prompts()
  File "c:\users\adith\anaconda3\envs\trials\lib\site-packages\onlyfans_scraper\scraper.py", line 199, in process_prompts
    headers = auth.make_headers(auth.read_auth())
  File "c:\users\adith\anaconda3\envs\trials\lib\site-packages\onlyfans_scraper\utils\auth.py", line 24, in read_auth
    make_request_auth()
  File "c:\users\adith\anaconda3\envs\trials\lib\site-packages\onlyfans_scraper\utils\auth.py", line 178, in make_request_auth
    with open(p, 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\adith\\.config\\onlyfans-scraper\\main_profile\\request_auth.json'

**Comment by Amenly** [comment]
Thanks for filing the issue. I'm surprised it took this long for someone to bring this up. If you upgrade to `1.7.2`, it should work now

```
pip install --upgrade onlyfans-scraper
```

**Comment by tetrahydr0** [comment]
same problem - 1.7.2.((

**Comment by adithyarao121** [comment]
I

> 
> 
> Thanks for filing the issue. I'm surprised it took this long for someone to bring this up. If you upgrade to `1.7.2`, it should work now
> 
> ```
> pip install --upgrade onlyfans-scraper
> ```

it is working now, thanks :)
