### ISSUE TITLE
auth.json Mac

### ISSUE THREAD

**Issue by 90fiifii90** [Amenly/onlyfans-scraper#40]
Can you add auth.json file?

**Comment by Amenly** [comment]
Could you post the full error message?

**Comment by 90fiifii90** [comment]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/onlyfans-scraper", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/onlyfans_scraper/scraper.py", line 321, in main
    process_prompts()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/onlyfans_scraper/scraper.py", line 218, in process_prompts
    model_id = profile.get_id(headers, username)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/onlyfans_scraper/api/profile.py", line 73, in get_id
    r.raise_for_status()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/httpx/_models.py", line 1402, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: 400 Client Error: Bad Request for url: https://onlyfans.com/api2/v2/users/indialove
For more information check: https://httpstatuses.com/400
