### ISSUE TITLE
Changed auth again

### ISSUE THREAD

**Issue by JajaDingDong** [Amenly/onlyfans-scraper#43]
Looks like they changed auth again? 

```
? Choose one of the following options:  Print a list of my subscriptions
Traceback (most recent call last):
  File "/usr/bin/onlyfans-scraper", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.9/site-packages/onlyfans_scraper/scraper.py", line 321, in main
    process_prompts()
  File "/usr/lib/python3.9/site-packages/onlyfans_scraper/scraper.py", line 268, in process_prompts
    loop()
  File "/usr/lib/python3.9/site-packages/onlyfans_scraper/scraper.py", line 209, in process_prompts
    subscribe_count = process_me(headers)
  File "/usr/lib/python3.9/site-packages/onlyfans_scraper/scraper.py", line 189, in process_me
    my_profile = me.scrape_user(headers)
  File "/usr/lib/python3.9/site-packages/onlyfans_scraper/api/me.py", line 26, in scrape_user
    r.raise_for_status()
  File "/usr/lib/python3.9/site-packages/httpx/_models.py", line 1402, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: 400 Client Error: Bad Request for url: https://onlyfans.com/api2/v2/users/me
For more information check: https://httpstatuses.com/400

```

**Comment by itsdavee316** [comment]
Could this be related to the site redesign, I'm having trouble as well.

? Choose one of the following options:  Print a list of my subscriptions
Traceback (most recent call last):
  File "/usr/local/bin/onlyfans-scraper", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/onlyfans_scraper/scraper.py", line 321, in main
    process_prompts()
  File "/usr/local/lib/python3.8/dist-packages/onlyfans_scraper/scraper.py", line 268, in process_prompts
    loop()
  File "/usr/local/lib/python3.8/dist-packages/onlyfans_scraper/scraper.py", line 209, in process_prompts
    subscribe_count = process_me(headers)
  File "/usr/local/lib/python3.8/dist-packages/onlyfans_scraper/scraper.py", line 189, in process_me
    my_profile = me.scrape_user(headers)
  File "/usr/local/lib/python3.8/dist-packages/onlyfans_scraper/api/me.py", line 26, in scrape_user
    r.raise_for_status()
  File "/usr/local/lib/python3.8/dist-packages/httpx/_models.py", line 1402, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: 400 Client Error: Bad Request for url: https://onlyfans.com/api2/v2/users/me
For more information check: https://httpstatuses.com/400
