### ISSUE TITLE
401 Client Error

### ISSUE THREAD

**Issue by mfp4073** [Amenly/onlyfans-scraper#55]
I've recloned the repo twice and still get 401 errors. This is new and the app worked fine 2 weeks ago - did OF change their API in a way that would break the app? 

Traceback (most recent call last):
  File "/usr/local/bin/onlyfans-scraper", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/onlyfans_scraper/scraper.py", line 321, in main
    process_prompts()
  File "/usr/local/lib/python3.9/site-packages/onlyfans_scraper/scraper.py", line 209, in process_prompts
    subscribe_count = process_me(headers)
  File "/usr/local/lib/python3.9/site-packages/onlyfans_scraper/scraper.py", line 189, in process_me
    my_profile = me.scrape_user(headers)
  File "/usr/local/lib/python3.9/site-packages/onlyfans_scraper/api/me.py", line 26, in scrape_user
    r.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/httpx/_models.py", line 1402, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: 401 Client Error: Unauthorized for url: https://onlyfans.com/api2/v2/users/me

**Comment by anoeks** [comment]
I've got same issue, 401 client error. Had to edit session info with current one and still no dice.
Traceback (most recent call last):
  File "c:\users\xxx\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\xxx\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python39\Scripts\onlyfans-scraper.exe\__main__.py", line 7, in <module>
  File "c:\users\xxx\appdata\local\programs\python\python39\lib\site-packages\onlyfans_scraper\scraper.py", line 321, in main
    process_prompts()
  File "c:\users\xxx\appdata\local\programs\python\python39\lib\site-packages\onlyfans_scraper\scraper.py", line 268, in process_prompts
    loop()
  File "c:\users\xxx\appdata\local\programs\python\python39\lib\site-packages\onlyfans_scraper\scraper.py", line 209, in process_prompts
    subscribe_count = process_me(headers)
  File "c:\users\xxx\appdata\local\programs\python\python39\lib\site-packages\onlyfans_scraper\scraper.py", line 189, in process_me
    my_profile = me.scrape_user(headers)
  File "c:\users\xxx\appdata\local\programs\python\python39\lib\site-packages\onlyfans_scraper\api\me.py", line 26, in scrape_user
    r.raise_for_status()
  File "c:\users\xxx\appdata\local\programs\python\python39\lib\site-packages\httpx\_models.py", line 1402, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: 401 Client Error: Unauthorized for url: https://onlyfans.com/api2/v2/users/me

**Comment by TWIISTED-STUDIOS** [comment]
The same issue worked last time tried, this month does not work.

**Comment by gers1978** [comment]
I had my `sess` value from the normal Chrome cookie viewer to avoid the 401 error, rather than Developer Tools,. demonstrated in this short video I made, hope this helps:

https://user-images.githubusercontent.com/4563945/170808582-c3d2b7b3-503d-4443-a6f2-535d7994abdb.mov

.
