### ISSUE TITLE
error 400

### ISSUE THREAD

**Issue by Crazylocust** [Amenly/onlyfans-scraper#64]
Hi everything was working fine, but I suddenly got this error, even after rechecking 5 times the infos

Am I missing something?

Thanks

 File "c:\users\arawn\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\arawn\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\arawn\AppData\Local\Programs\Python\Python39\Scripts\onlyfans-scraper.exe\__main__.py", line 7, in <module>
  File "c:\users\arawn\appdata\local\programs\python\python39\lib\site-packages\onlyfans_scraper\scraper.py", line 321, in main
    process_prompts()
  File "c:\users\arawn\appdata\local\programs\python\python39\lib\site-packages\onlyfans_scraper\scraper.py", line 268, in process_prompts
    loop()
  File "c:\users\arawn\appdata\local\programs\python\python39\lib\site-packages\onlyfans_scraper\scraper.py", line 218, in process_prompts
    model_id = profile.get_id(headers, username)
  File "c:\users\arawn\appdata\local\programs\python\python39\lib\site-packages\onlyfans_scraper\api\profile.py", line 73, in get_id
    r.raise_for_status()
  File "c:\users\arawn\appdata\local\programs\python\python39\lib\site-packages\httpx\_models.py", line 1402, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: 400 Client Error: Bad Request for url: https://onlyfans.com/api2/v2/users/theemilylynne
For more information check: https://httpstatuses.com/400

**Comment by Amenly** [comment]
It's working fine for me which means it's probably something on your end.

Did you recently update your browser (which means the user agent might be different)? Are you using the same profile you always use or did you switch to another profile and forget to switch back to your main profile?

**Comment by Crazylocust** [comment]
Oh that's it, the browser automatically updated. Thanks!

**Comment by havingfun2500** [comment]
Hey @Amenly, I have the same error 400 and I cannot figure out why. I updated the json file using both Chrome & Safari and it still return the error. If it helps, I use macOS and it didn't ask for my x-bc when setting up. This is my traceback.

Traceback (most recent call last):
  File "/Users/apple/Library/Python/3.8/bin/onlyfans-scraper", line 8, in <module>
    sys.exit(main())
  File "/Users/apple/Library/Python/3.8/lib/python/site-packages/onlyfans_scraper/scraper.py", line 212, in main
    subscribe_count = process_me(headers)
  File "/Users/apple/Library/Python/3.8/lib/python/site-packages/onlyfans_scraper/scraper.py", line 185, in process_me
    my_profile = me.scrape_user(headers)
  File "/Users/apple/Library/Python/3.8/lib/python/site-packages/onlyfans_scraper/api/me.py", line 21, in scrape_user
    r.raise_for_status()
  File "/Users/apple/Library/Python/3.8/lib/python/site-packages/httpx/_models.py", line 1105, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: 400 Client Error: Bad Request for url: https://onlyfans.com/api2/v2/users/me
For more information check: https://httpstatuses.com/400

The url request "https://onlyfans.com/api2/v2/users/me" seems to be different than before, without the exact username.

**Comment by Amenly** [comment]
@havingfun2500 It didn't ask for your x-bc token? Which version are you using?

Go to your terminal and enter the following:

```
python3
```

That will activate the Python interpreter. Once the interpreter is open, enter the following commands (don't include the '>>>'s):

```
>>> import onlyfans_scraper
>>> onlyfans-scraper.__version__
```

Then tell me the version number.

**Comment by UT07** [comment]
I'm also having the same error.
`Traceback (most recent call last):
  File "c:\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python39\Scripts\onlyfans-scraper.exe\__main__.py", line 7, in <module>
  File "c:\python39\lib\site-packages\onlyfans_scraper\scraper.py", line 321, in main
    process_prompts()
  File "c:\python39\lib\site-packages\onlyfans_scraper\scraper.py", line 268, in process_prompts
    loop()
  File "c:\python39\lib\site-packages\onlyfans_scraper\scraper.py", line 218, in process_prompts
    model_id = profile.get_id(headers, username)
  File "c:\python39\lib\site-packages\onlyfans_scraper\api\profile.py", line 73, in get_id
    r.raise_for_status()
  File "c:\python39\lib\site-packages\httpx\_models.py", line 841, in raise_for_status
    raise HTTPError(message, response=self)
httpx._exceptions.HTTPError: 400 Client Error: Bad Request for url: https://onlyfans.com/api2/v2/users/poonampandeytv
For more information check: https://httpstatuses.com/400`

**Comment by Amenly** [comment]
@UT07 Did you recently update your browser?

**Comment by tdex89** [comment]
I'm getting a similar fault as well.

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/onlyfans-scraper", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/onlyfans_scraper/scraper.py", line 321, in main
    process_prompts()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/onlyfans_scraper/scraper.py", line 209, in process_prompts
    subscribe_count = process_me(headers)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/onlyfans_scraper/scraper.py", line 189, in process_me
    my_profile = me.scrape_user(headers)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/onlyfans_scraper/api/me.py", line 26, in scrape_user
    r.raise_for_status()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/httpx/_models.py", line 1402, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: 400 Client Error: Bad Request for url: https://onlyfans.com/api2/v2/users/me
For more information check: https://httpstatuses.com/400

**Comment by havingfun2500** [comment]
@Amenly Hi, just little update. Turn out I was using the ~1.7.2 version which didn't ask for 'x-bc' value. After I uninstalled the old version and installed the new one using pip3 command, the program still ran into error because there is no 'x-bc' value in the "auth.json" file. I surmised that when I uninstalled the old version, it didn't delete the old "auth.json" file so the new version automatically use it without creating a new one. After a few hours of head scratching, I found the "auth.json" file in .config and threw the whole thing into the trash and your script now works as good as new. 

I think the you can add a section to readme on how to manually access and troubleshoot the "auth.json" file since it seems many people are having 400 error.
