### ISSUE TITLE
Crashes when retrieving some models

### ISSUE THREAD

**Issue by tocking** [Amenly/onlyfans-scraper#7]
- 0 archived posts
 \ Getting pinned media...
Traceback (most recent call last):
  File "c:\users\<USERNAME>\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\<USERNAME>\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\<USERNAME>\AppData\Local\Programs\Python\Python39\Scripts\onlyfans-scraper.exe\__main__.py", line 7, in <module>
  File "c:\users\<USERNAME>\appdata\local\programs\python\python39\lib\site-packages\onlyfans_scraper\scraper.py", line 216, in main
    do_download_content(headers, username, model_id)
  File "c:\users\<USERNAME>\appdata\local\programs\python\python39\lib\site-packages\onlyfans_scraper\scraper.py", line 123, in do_download_content
    combined_urls = process_areas(headers, username, model_id)
  File "c:\users\<USERNAME>\appdata\local\programs\python\python39\lib\site-packages\onlyfans_scraper\scraper.py", line 94, in process_areas
    timeline_posts_urls = process_timeline_posts(headers, model_id)
  File "c:\users\<USERNAME>\appdata\local\programs\python\python39\lib\site-packages\revolution\revolution.py", line 31, in wrapper
    result = func(*margs, **mkwargs)
  File "c:\users\<USERNAME>\appdata\local\programs\python\python39\lib\site-packages\onlyfans_scraper\scraper.py", line 59, in process_timeline_posts
    timeline_posts_urls = posts.parse_posts(timeline_posts)
  File "c:\users\<USERNAME>\appdata\local\programs\python\python39\lib\site-packages\onlyfans_scraper\api\posts.py", line 56, in parse_posts
    media = [post['media'] for post in posts if post['media']]
  File "c:\users\<USERNAME>\appdata\local\programs\python\python39\lib\site-packages\onlyfans_scraper\api\posts.py", line 56, in <listcomp>
    media = [post['media'] for post in posts if post['media']]
KeyError: 'media'
 | Getting timeline media...

**Comment by Amenly** [comment]
Could you tell me which version you're using? I've been working on updates for the scraper so it's a little difficult to really see the full path of the error. 

There's two ways you can use to find the version number. Either by entering `pip freeze` in your terminal and then telling me the numbers after `onlyfans-scraper==` or by entering the Python interpreter:

```
$ python

>>> import onlyfans_scraper
>>> onlyfans_scraper.__version__
```

**Comment by tocking** [comment]
Sure.

onlyfans-scraper==0.3.2

**Comment by Amenly** [comment]
Huh, that's very weird. Nothing's immediately jumping at me as to why it would crash at that specific point...

The only thing I can think of is maybe there's some **type** of post on OnlyFans that can *never* contain 'media' and the user you scraped has that **type** of post on their timeline.

Is there any chance you could give me the username(s) of the person/people you used the script on and it crashed? There's actually a good chance I might have access to their accounts.

**Comment by tocking** [comment]
rhoneeandkhoa

**Comment by Amenly** [comment]
Unfortunately, I'm not subbed to either of those accounts but luckily they have their timelines public so I'm going to look through what's available and see if there's some *type* of post that the scraper doesn't know how to handle. Thank you for the usernames though.

I know for sure that it's able to handle regular posts with images/videos/audios, polls, locked posts, and locked posts with previews...I wonder if there's something missing or if they recently introduced a new type of post.

**Comment by Amenly** [comment]
Because I can view their timelines, I can still scrape their timelines but I won't be able to view *any* media or download anything. I ran the script on both of them and I was able to scrape both of their timelines without crashing. Are you sure it crashed for you for both of them?

**Comment by tocking** [comment]
Yep, have tried it multiple times.  For what it's worth, they both crash DIGITALCRIMINAL's script too...

**Comment by tocking** [comment]
Figured out what's cuasing this (via DIGITALCRIMINAL's script) - but not sure how to fix it.  The crash occurs when the scraper tries to process a post that's previously been reported.  Is there any way to detect this and skip over it?

**Comment by Amenly** [comment]
That makes sense why the API would refuse to display any media if you reported the post. I'll see what I can do.

**Comment by Amenly** [comment]
@tocking Try using the latest version (1.0.2):

```
pip install --upgrade onlyfans-scraper
```

It should skip reported posts now

**Comment by KemMuammer** [comment]
Hi get the "same" failure. I update it to the latest version. 

It spits this out and I couldn't find the issue.(I am not so familiar with reading code)
Traceback (most recent call last):
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\KemMuammer\AppData\Local\Programs\Python\Python39\Scripts\onlyfans-scraper.exe\__main__.py", line 7, in <module>
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\onlyfans_scraper\scraper.py", line 321, in main
    process_prompts()
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\onlyfans_scraper\scraper.py", line 213, in process_prompts
    do_download_content(headers, username, model_id)
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\onlyfans_scraper\scraper.py", line 141, in do_download_content
    asyncio.run(download.process_urls(
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\onlyfans_scraper\utils\download.py", line 59, in process_urls
    total_bytes_downloaded += num_bytes_downloaded
UnboundLocalError: local variable 'num_bytes_downloaded' referenced before assignment
Task exception was never retrieved
future: <Task finished name='Task-29' coro=<download() done, defined at c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\onlyfans_scraper\utils\download.py:85> exception=ConnectError('[Errno 11001] getaddrinfo failed')>
Traceback (most recent call last):
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\httpx\_transports\default.py", line 61, in map_httpcore_exceptions
    yield
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\httpx\_transports\default.py", line 279, in handle_async_request
    ) = await self._pool.handle_async_request(
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\httpcore\_async\connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\httpcore\_async\connection.py", line 136, in handle_async_request
    self.socket = await self._open_socket(timeout)
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\httpcore\_async\connection.py", line 163, in _open_socket
    return await self._backend.open_tcp_stream(
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\httpcore\_backends\auto.py", line 44, in open_tcp_stream
    return await self.backend.open_tcp_stream(
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\httpcore\_backends\anyio.py", line 152, in open_tcp_stream
    stream = await TLSStream.wrap(
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\httpcore\_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc) from None
httpcore.ConnectError: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\onlyfans_scraper\utils\download.py", line 91, in download
    async with client.stream('GET', url) as r:
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\contextlib.py", line 175, in __aenter__
    return await self.gen.__anext__()
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\httpx\_client.py", line 1468, in stream
    response = await self.send(
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\httpx\_client.py", line 1510, in send
    response = await self._send_handling_auth(
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\httpx\_client.py", line 1545, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\httpx\_client.py", line 1579, in _send_handling_redirects
    response = await self._send_single_request(request, timeout)
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\httpx\_client.py", line 1620, in _send_single_request
    ) = await transport.handle_async_request(
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\httpx\_transports\default.py", line 274, in handle_async_request
    (
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\httpx\_transports\default.py", line 78, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno 11001] getaddrinfo failed
Task exception was never retrieved
future: <Task finished name='Task-28' coro=<download() done, defined at c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\onlyfans_scraper\utils\download.py:85> exception=ConnectError('[Errno 11001] getaddrinfo failed')>
Traceback (most recent call last):
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\httpx\_transports\default.py", line 61, in map_httpcore_exceptions
    yield
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\httpx\_transports\default.py", line 279, in handle_async_request
    ) = await self._pool.handle_async_request(
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\httpcore\_async\connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\httpcore\_async\connection.py", line 136, in handle_async_request
    self.socket = await self._open_socket(timeout)
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\httpcore\_async\connection.py", line 163, in _open_socket
    return await self._backend.open_tcp_stream(
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\httpcore\_backends\auto.py", line 44, in open_tcp_stream
    return await self.backend.open_tcp_stream(
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\httpcore\_backends\anyio.py", line 152, in open_tcp_stream
    stream = await TLSStream.wrap(
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\httpcore\_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc) from None
httpcore.ConnectError: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\onlyfans_scraper\utils\download.py", line 91, in download
    async with client.stream('GET', url) as r:
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\contextlib.py", line 175, in __aenter__
    return await self.gen.__anext__()
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\httpx\_client.py", line 1468, in stream
    response = await self.send(
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\httpx\_client.py", line 1510, in send
    response = await self._send_handling_auth(
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\httpx\_client.py", line 1545, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\httpx\_client.py", line 1579, in _send_handling_redirects
    response = await self._send_single_request(request, timeout)
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\httpx\_client.py", line 1620, in _send_single_request
    ) = await transport.handle_async_request(
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\httpx\_transports\default.py", line 274, in handle_async_request
    (
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\httpx\_transports\default.py", line 78, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno 11001] getaddrinfo failed
Task exception was never retrieved
future: <Task finished name='Task-27' coro=<download() done, defined at c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\onlyfans_scraper\utils\download.py:85> exception=ConnectError('[Errno 11001] getaddrinfo failed')>
Traceback (most recent call last):
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\httpx\_transports\default.py", line 61, in map_httpcore_exceptions
    yield
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\httpx\_transports\default.py", line 279, in handle_async_request
    ) = await self._pool.handle_async_request(
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\httpcore\_async\connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\httpcore\_async\connection.py", line 136, in handle_async_request
    self.socket = await self._open_socket(timeout)
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\httpcore\_async\connection.py", line 163, in _open_socket
    return await self._backend.open_tcp_stream(
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\httpcore\_backends\auto.py", line 44, in open_tcp_stream
    return await self.backend.open_tcp_stream(
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\httpcore\_backends\anyio.py", line 152, in open_tcp_stream
    stream = await TLSStream.wrap(
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\httpcore\_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc) from None
httpcore.ConnectError: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\onlyfans_scraper\utils\download.py", line 91, in download
    async with client.stream('GET', url) as r:
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\contextlib.py", line 175, in __aenter__
    return await self.gen.__anext__()
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\httpx\_client.py", line 1468, in stream
    response = await self.send(
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\httpx\_client.py", line 1510, in send
    response = await self._send_handling_auth(
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\httpx\_client.py", line 1545, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\httpx\_client.py", line 1579, in _send_handling_redirects
    response = await self._send_single_request(request, timeout)
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\httpx\_client.py", line 1620, in _send_single_request
    ) = await transport.handle_async_request(
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\httpx\_transports\default.py", line 274, in handle_async_request
    (
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\httpx\_transports\default.py", line 78, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno 11001] getaddrinfo failed
Task exception was never retrieved
future: <Task finished name='Task-26' coro=<download() done, defined at c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\onlyfans_scraper\utils\download.py:85> exception=ConnectError('[Errno 11001] getaddrinfo failed')>
Traceback (most recent call last):
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\httpx\_transports\default.py", line 61, in map_httpcore_exceptions
    yield
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\httpx\_transports\default.py", line 279, in handle_async_request
    ) = await self._pool.handle_async_request(
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\httpcore\_async\connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\httpcore\_async\connection.py", line 136, in handle_async_request
    self.socket = await self._open_socket(timeout)
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\httpcore\_async\connection.py", line 163, in _open_socket
    return await self._backend.open_tcp_stream(
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\httpcore\_backends\auto.py", line 44, in open_tcp_stream
    return await self.backend.open_tcp_stream(
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\httpcore\_backends\anyio.py", line 152, in open_tcp_stream
    stream = await TLSStream.wrap(
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\httpcore\_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc) from None
httpcore.ConnectError: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\onlyfans_scraper\utils\download.py", line 91, in download
    async with client.stream('GET', url) as r:
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\contextlib.py", line 175, in __aenter__
    return await self.gen.__anext__()
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\httpx\_client.py", line 1468, in stream
    response = await self.send(
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\httpx\_client.py", line 1510, in send
    response = await self._send_handling_auth(
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\httpx\_client.py", line 1545, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\httpx\_client.py", line 1579, in _send_handling_redirects
    response = await self._send_single_request(request, timeout)
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\httpx\_client.py", line 1620, in _send_single_request
    ) = await transport.handle_async_request(
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\httpx\_transports\default.py", line 274, in handle_async_request
    (
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\httpx\_transports\default.py", line 78, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno 11001] getaddrinfo failed
Task exception was never retrieved
future: <Task finished name='Task-24' coro=<download() done, defined at c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\onlyfans_scraper\utils\download.py:85> exception=ClosedResourceError()>
Traceback (most recent call last):
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\onlyfans_scraper\utils\download.py", line 91, in download
    async with client.stream('GET', url) as r:
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\contextlib.py", line 175, in __aenter__
    return await self.gen.__anext__()
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\httpx\_client.py", line 1468, in stream
    response = await self.send(
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\httpx\_client.py", line 1510, in send
    response = await self._send_handling_auth(
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\httpx\_client.py", line 1545, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\httpx\_client.py", line 1579, in _send_handling_redirects
    response = await self._send_single_request(request, timeout)
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\httpx\_client.py", line 1620, in _send_single_request
    ) = await transport.handle_async_request(
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\httpx\_transports\default.py", line 279, in handle_async_request
    ) = await self._pool.handle_async_request(
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\httpcore\_async\connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\httpcore\_async\connection.py", line 148, in handle_async_request
    return await self.connection.handle_async_request(
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\httpcore\_async\http11.py", line 128, in handle_async_request
    ) = await self._receive_response(timeout)
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\httpcore\_async\http11.py", line 189, in _receive_response
    event = await self._receive_event(timeout)
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\httpcore\_async\http11.py", line 225, in _receive_event
    data = await self.socket.read(self.READ_NUM_BYTES, timeout)
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\httpcore\_backends\anyio.py", line 60, in read
    return await self.stream.receive(n)
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\anyio\streams\tls.py", line 152, in receive
    data = await self._call_sslobject_method(self._ssl_object.read, max_bytes)
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\anyio\streams\tls.py", line 109, in _call_sslobject_method
    data = await self.transport_stream.receive()
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\anyio\_backends\_asyncio.py", line 1083, in receive
    raise ClosedResourceError from None
anyio.ClosedResourceError
Task exception was never retrieved
future: <Task finished name='Task-23' coro=<download() done, defined at c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\onlyfans_scraper\utils\download.py:85> exception=ClosedResourceError()>
Traceback (most recent call last):
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\onlyfans_scraper\utils\download.py", line 91, in download
    async with client.stream('GET', url) as r:
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\contextlib.py", line 175, in __aenter__
    return await self.gen.__anext__()
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\httpx\_client.py", line 1468, in stream
    response = await self.send(
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\httpx\_client.py", line 1510, in send
    response = await self._send_handling_auth(
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\httpx\_client.py", line 1545, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\httpx\_client.py", line 1579, in _send_handling_redirects
    response = await self._send_single_request(request, timeout)
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\httpx\_client.py", line 1620, in _send_single_request
    ) = await transport.handle_async_request(
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\httpx\_transports\default.py", line 279, in handle_async_request
    ) = await self._pool.handle_async_request(
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\httpcore\_async\connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\httpcore\_async\connection.py", line 148, in handle_async_request
    return await self.connection.handle_async_request(
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\httpcore\_async\http11.py", line 128, in handle_async_request
    ) = await self._receive_response(timeout)
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\httpcore\_async\http11.py", line 189, in _receive_response
    event = await self._receive_event(timeout)
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\httpcore\_async\http11.py", line 225, in _receive_event
    data = await self.socket.read(self.READ_NUM_BYTES, timeout)
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\httpcore\_backends\anyio.py", line 60, in read
    return await self.stream.receive(n)
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\anyio\streams\tls.py", line 152, in receive
    data = await self._call_sslobject_method(self._ssl_object.read, max_bytes)
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\anyio\streams\tls.py", line 109, in _call_sslobject_method
    data = await self.transport_stream.receive()
  File "c:\users\kemmuammer\appdata\local\programs\python\python39\lib\site-packages\anyio\_backends\_asyncio.py", line 1083, in receive
    raise ClosedResourceError from None
anyio.ClosedResourceError


maybe this can help? 

Should I open a new ticket for this?
