### ISSUE TITLE
Standard 401 Client Error: Unauthorized for url

### ISSUE THREAD

**Issue by blackziploc** [Amenly/onlyfans-scraper#85]
Double checked user agent and re-made profile from scratch. Just noticed it happening August 5th

Using profile: main_profile
Status - UP
? What would you like to do?  Download content from a user
? Choose one of the following options:  Scrape all users that I'm subscribed to
? Are you sure you want to scrape every model that you're subscribed to?  Yes
Traceback (most recent call last):
  File "c:\users\alex\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\alex\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python39\Scripts\onlyfans-scraper.exe\__main__.py", line 7, in <module>
  File "c:\users\alex\appdata\local\programs\python\python39\lib\site-packages\onlyfans_scraper\scraper.py", line 328, in main
    process_prompts()
  File "c:\users\alex\appdata\local\programs\python\python39\lib\site-packages\onlyfans_scraper\scraper.py", line 228, in process_prompts
    subscribe_count = process_me(headers)
  File "c:\users\alex\appdata\local\programs\python\python39\lib\site-packages\onlyfans_scraper\scraper.py", line 189, in process_me
    my_profile = me.scrape_user(headers)
  File "c:\users\alex\appdata\local\programs\python\python39\lib\site-packages\onlyfans_scraper\api\me.py", line 26, in scrape_user
    r.raise_for_status()
  File "c:\users\alex\appdata\local\programs\python\python39\lib\site-packages\httpx\_models.py", line 841, in raise_for_status
    raise HTTPError(message, response=self)
httpx._exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://onlyfans.com/api2/v2/users/me
For more information check: https://httpstatuses.com/401

**Comment by p5ismyname** [comment]
yeah thats what also happens to me i double checked the settings and it still doesnt work

**Comment by Amenly** [comment]
I just tested it on two accounts: one with 2FA enabled and one without. They both worked, meaning it's something in your `auth`. Can't really help you with it since I can't see your Network Requests tab in your browser.

**Comment by blackziploc** [comment]
Figured it out for myself. The guide does now seem to show the correct "sess" cookie. 
The correct "sess" cookie is located under "set-cookie:" which is located above the "cookie:" section and is way longer. I'll close this issue up with the answer here in case others ask, but I'd also add to the guide just in case. Cheers!

**Comment by p5ismyname** [comment]
doesnt work for me

**Comment by gers1978** [comment]
> doesnt work for me

I had my `sess` value from the normal Chrome cookie viewer to avoid the 401 error, rather than Developer Tools,. demonstrated in this short video I made, hope this helps:

https://user-images.githubusercontent.com/4563945/170808582-c3d2b7b3-503d-4443-a6f2-535d7994abdb.mov

.
