### ISSUE TITLE
'httpx' has no attribute 'Limits'

### ISSUE THREAD

**Issue by blackziploc** [Amenly/onlyfans-scraper#86]
Seems like I'm just good at breaking programs... Fixed the "sess" cookie issue so all subs show properly now. Now dealing with some scraper stuff. 

Traceback (most recent call last):
  File "c:\users\USER\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\USER\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python39\Scripts\onlyfans-scraper.exe\__main__.py", line 7, in <module>
  File "c:\users\USER\appdata\local\programs\python\python39\lib\site-packages\onlyfans_scraper\scraper.py", line 328, in main
    process_prompts()
  File "c:\users\USER\appdata\local\programs\python\python39\lib\site-packages\onlyfans_scraper\scraper.py", line 214, in process_prompts
    do_download_content(headers, username, model_id)
  File "c:\users\USER\appdata\local\programs\python\python39\lib\site-packages\onlyfans_scraper\scraper.py", line 141, in do_download_content
    asyncio.run(download.process_urls(
  File "c:\users\USER\appdata\local\programs\python\python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "c:\users\USER\appdata\local\programs\python\python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "c:\users\USER\appdata\local\programs\python\python39\lib\site-packages\onlyfans_scraper\utils\download.py", line 48, in process_urls
    limits = httpx.Limits(max_connections=8, max_keepalive_connections=5)
AttributeError: module 'httpx' has no attribute 'Limits'

**Comment by Amenly** [comment]
That's very strange. Could you run the following command in your terminal and tell me what version number shows up:

```
python -c "import httpx; print(httpx.__version__)"
```

**Comment by blackziploc** [comment]
Got it. Response is 0.13.3

**Comment by Amenly** [comment]
You're using a pretty old version of it. Try upgrading it if you don't need that specific version for anything:

```
pip install --upgrade httpx[http2]
```

**Comment by blackziploc** [comment]
Awesome! Yeah, I did need the older version for something, but I can just downgrade whenever I need it. Thanks for the help
