### ISSUE TITLE
AttributeError: module 'onlyfans_scraper.api.init' has no attribute 'print_sign_status'

### ISSUE THREAD

**Issue by steeph-k** [Amenly/onlyfans-scraper#93]
I managed to install onlyfans-scraper with the setup.py file from this package. I'm very inexperienced with python and didn't find an other way.

On the first run I could enter the values for auth.json. This seems to have worked. But afterwards I got this message:

    Traceback (most recent call last):
      File "/home/steeph/Downloads/OnlyFans-master/venv/bin/onlyfans-scraper", line 33, in <module>
        sys.exit(load_entry_point('onlyfans-scraper==1.8.0', 'console_scripts', 'onlyfans-scraper')())
      File "/home/steeph/Downloads/OnlyFans-master/venv/lib/python3.9/site-packages/onlyfans_scraper-1.8.0-py3.9.egg/onlyfans_scraper/scraper.py", line 328, in main
        process_prompts()
      File "/home/steeph/Downloads/OnlyFans-master/venv/lib/python3.9/site-packages/onlyfans_scraper-1.8.0-py3.9.egg/onlyfans_scraper/scraper.py", line 200, in process_prompts
        init.print_sign_status(headers)
    AttributeError: module 'onlyfans_scraper.api.init' has no attribute 'print_sign_status'

When running the script again this message is only preceded by the line `Using profile: main_profile`.

I couldn't find anything that gave me any idea what could be wrong. Is there anything I can try?

**Comment by lemming01** [comment]
I'm in the same boat.  New to Python and getting the following errors.  I was able to find and fill in the auth.json info.

C:\Users\[ ]\AppData\Local\Programs\Python\Python39\Scripts>onlyfans-scraper
Using profile: main_profile
Traceback (most recent call last):
  File "C:\Users\[ ]\AppData\Local\Programs\Python\Python39\Scripts\onlyfans-scraper-script.py", line 33, in <module>
    sys.exit(load_entry_point('onlyfans-scraper==1.8.0', 'console_scripts', 'onlyfans-scraper')())
  File "C:\Users\[ ]\AppData\Local\Programs\Python\Python39\lib\site-packages\onlyfans_scraper-1.8.0-py3.9.egg\onlyfans_scraper\scraper.py", line 328, in main
    process_prompts()
  File "C:\Users\[ ]\AppData\Local\Programs\Python\Python39\lib\site-packages\onlyfans_scraper-1.8.0-py3.9.egg\onlyfans_scraper\scraper.py", line 200, in process_prompts
    init.print_sign_status(headers)
AttributeError: module 'onlyfans_scraper.api.init' has no attribute 'print_sign_status'

**Comment by End3r-Duty** [comment]
I'm getting this error too. RIP support
