### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by NoNotNate** [Amenly/onlyfans-scraper#97]
File "c:\users\65445\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\65445\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\65445\AppData\Local\Programs\Python\Python39\Scripts\onlyfans-scraper.exe\__main__.py", line 7, in <module>
  File "c:\users\65445\appdata\local\programs\python\python39\lib\site-packages\onlyfans_scraper\scraper.py", line 328, in main
    process_prompts()
  File "c:\users\65445\appdata\local\programs\python\python39\lib\site-packages\onlyfans_scraper\scraper.py", line 243, in process_prompts
    unfavorited_posts = like.filter_for_unfavorited(posts)
  File "c:\users\65445\appdata\local\programs\python\python39\lib\site-packages\onlyfans_scraper\interaction\like.py", line 31, in filter_for_unfavorited
    unfavorited_posts = [post for post in posts if not post['isFavorite']]
  File "c:\users\65445\appdata\local\programs\python\python39\lib\site-packages\onlyfans_scraper\interaction\like.py", line 31, in <listcomp>
    unfavorited_posts = [post for post in posts if not post['isFavorite']]
KeyError: 'isFavorite'

**Comment by tetrahydr0** [comment]
Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\user\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\Scripts\onlyfans-scraper.exe\__main__.py", line 7, in <module>
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\onlyfans_scraper\scraper.py", line 328, in main
    process_prompts()
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\onlyfans_scraper\scraper.py", line 269, in process_prompts
    loop()
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\onlyfans_scraper\scraper.py", line 269, in process_prompts
    loop()
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\onlyfans_scraper\scraper.py", line 240, in process_prompts
    model_id = profile.get_id(headers, username)
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\onlyfans_scraper\api\profile.py", line 73, in get_id
    r.raise_for_status()
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\httpx\_models.py", line 1423, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: 400 Client Error: Bad Request for url: https://onlyfans.com/api2/v2/users/fitfager
For more information check: https://httpstatuses.com/400
